driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  run_list:
  - recipe[apt]

- name: centos-6.5

suites:
- name: tomcat6
  run_list: ["recipe[tomcat]"]
  attributes: {}

- name: tomcat7
  run_list: ["recipe[tomcat]"]
  excludes: ["ubuntu-10.04", "centos-6.5"]
  attributes: {tomcat: {base_version: 7}}
