#cookbook 'unicorn', github: 'aws/opsworks-cookbooks', rel: 'unicorn'
cookbook 'nginx', github: 'aws/opsworks-cookbooks', rel: 'nginx'
cookbook 'deploy', github: 'aws/opsworks-cookbooks', rel: 'deploy'
cookbook 'apache2', github: 'aws/opsworks-cookbooks', rel: 'apache2'
cookbook 'corndog-chef', :git => 'https://github.com/CDEI/corndog-chef.git'
cookbook 'base-opsworks', :git => 'https://github.com/CDEI/base-opsworks.git'
cookbook 'apt', :git => 'https://github.com/opscode-cookbooks/apt.git'
